nelmio_cors:
    defaults:
        allow_credentials: false
        allow_origin: ['*']
        allow_headers: ['Content-type', 'Authorization', 'Origin']
        allow_methods: ['OPTIONS', 'POST']
        expose_headers: ['Link']
        max_age: 3600
        origin_regex: false
        forced_allow_origin_value: ~
    paths:
        '^/': ~
